### ISSUE TITLE
Allow changing port and host

### ISSUE THREAD

**Issue by jpoehnelt** [cedricdelpoux/google-oauth2-env-vars#2]
In my particular setup I needed to change the host to get this working. These options might be nice to include.

**Comment by cedricdelpoux** [comment]
You are right, it could be an option. Do you want to make a PR about this?

**Comment by cedricdelpoux** [comment]
Hi @jpoehnelt, I added a port option

**Comment by cedricdelpoux** [comment]
Checkout `v1.3.0`
